name: CI/CD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repo
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - name: Setting up Python environment
      run: python3 -m venv venv
    - run: source venv/bin/activate
    - run: mkdir package

    - name: Installing packages
      run: pip install -r requirements.txt --target ./package

    - name: Deplying to AWS Lambda
      run: ./deploy.sh
